// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6lN3RoEoicBC2nKAH2hPN1vkBBc9k0z8',
    appId: '1:244224933068:android:b31b8cc62563c778005669',
    messagingSenderId: '244224933068',
    projectId: 'myhouseuser-6b486',
    databaseURL: 'https://myhouseuser-6b486-default-rtdb.firebaseio.com',
    storageBucket: 'myhouseuser-6b486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2FmwcYzvs5Cu5Aq6IygnWCg47ZI0AkD0',
    appId: '1:244224933068:ios:38c61538ad569107005669',
    messagingSenderId: '244224933068',
    projectId: 'myhouseuser-6b486',
    databaseURL: 'https://myhouseuser-6b486-default-rtdb.firebaseio.com',
    storageBucket: 'myhouseuser-6b486.appspot.com',
    iosBundleId: 'com.example.myhouseuser',
  );
}
